# Generated by Django 5.1.1 on 2024-09-06 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_alter_badge_owners'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='badge',
            old_name='badget_picture',
            new_name='badge_picture',
        ),
        migrations.AlterField(
            model_name='badge',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='badges_own', to=settings.AUTH_USER_MODEL),
        ),
    ]
