# Generated by Django 5.1.1 on 2024-09-08 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_rename_badget_picture_badge_badge_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badge',
            old_name='badge_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='badge',
            old_name='badge_picture',
            new_name='picture',
        ),
    ]
